/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 5.5.40 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `tb_order` (
	`order_id` bigint (20),
	`payment` Decimal (22),
	`payment_type` varchar (3),
	`post_fee` varchar (150),
	`status` varchar (3),
	`create_time` datetime ,
	`update_time` datetime ,
	`payment_time` datetime ,
	`consign_time` datetime ,
	`end_time` datetime ,
	`close_time` datetime ,
	`shipping_name` varchar (60),
	`shipping_code` varchar (60),
	`user_id` varchar (150),
	`buyer_message` varchar (300),
	`buyer_nick` varchar (150),
	`buyer_rate` varchar (6),
	`receiver_area_name` varchar (300),
	`receiver_mobile` varchar (36),
	`receiver_zip_code` varchar (45),
	`receiver` varchar (150),
	`expire` datetime ,
	`invoice_type` varchar (3),
	`source_type` varchar (3),
	`seller_id` varchar (300),
	`order_id_str` varchar (150)
); 
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('1',NULL,'1',NULL,'0','2017-08-24 20:42:25','2017-08-24 20:42:25',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('2',NULL,'1',NULL,'0','2017-08-24 20:44:03','2017-08-24 20:44:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('3','3.00','1',NULL,'0','2017-08-24 20:46:10','2017-08-24 20:46:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('4','266.64','1',NULL,'0','2017-08-24 20:46:11','2017-08-24 20:46:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('5','299.97','1',NULL,'0','2017-08-24 20:46:11','2017-08-24 20:46:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('6','3.00','1',NULL,'0','2017-08-24 20:46:40','2017-08-24 20:46:40',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('7','266.64','1',NULL,'0','2017-08-24 20:46:40','2017-08-24 20:46:40',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('8','299.97','1',NULL,'0','2017-08-24 20:46:40','2017-08-24 20:46:40',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('9','3.00','1',NULL,'0','2017-08-24 21:01:10','2017-08-24 21:01:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('10','266.64','1',NULL,'0','2017-08-24 21:01:11','2017-08-24 21:01:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('11','299.97','1',NULL,'0','2017-08-24 21:01:11','2017-08-24 21:01:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('12','3.00','1',NULL,'0','2017-08-24 21:05:56','2017-08-24 21:05:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('13','266.64','1',NULL,'0','2017-08-24 21:05:56','2017-08-24 21:05:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('14','299.97','1',NULL,'0','2017-08-24 21:05:56','2017-08-24 21:05:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('15','3.00','1',NULL,'0','2017-08-24 23:07:38','2017-08-24 23:07:38',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('16','266.64','1',NULL,'0','2017-08-24 23:07:38','2017-08-24 23:07:38',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('17','299.97','1',NULL,'0','2017-08-24 23:07:38','2017-08-24 23:07:38',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('18','177.76','1',NULL,'1','2017-08-25 11:59:03','2017-08-25 11:59:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'yijia',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('19','2.00','1',NULL,'1','2017-08-25 11:59:03','2017-08-25 11:59:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('20','177.76','1',NULL,'1','2017-08-25 11:59:03','2017-08-25 11:59:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'yijia',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('21','177.76','1',NULL,'1','2017-08-25 23:26:10','2017-08-25 23:26:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('22','2.00','1',NULL,'1','2017-08-25 23:26:11','2017-08-25 23:26:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('23','177.76','1',NULL,'1','2017-08-25 23:26:11','2017-08-25 23:26:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('24','2.00','1',NULL,'1','2017-08-25 23:28:10','2017-08-25 23:28:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('25','1.00','1',NULL,'1','2017-08-25 23:49:18','2017-08-25 23:49:18',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('26','0.01','1',NULL,'1','2017-08-26 00:06:31','2017-08-26 00:06:31',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'修正大厦','13700221122',NULL,'李佳红',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('27','0.01','1',NULL,'1','2017-08-26 00:10:13','2017-08-26 00:10:13',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('28','0.01','1',NULL,'1','2017-08-26 00:17:53','2017-08-26 00:17:53',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('29','0.01','1',NULL,'1','2017-08-26 00:19:56','2017-08-26 00:19:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('30','0.01','1',NULL,'1','2017-08-26 00:37:47','2017-08-26 00:37:47',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('31','0.02','1',NULL,'1','2017-08-26 00:37:47','2017-08-26 00:37:47',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('32','0.02','1',NULL,'2','2017-08-26 00:41:13','2017-08-26 00:41:13',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('33','0.01','1',NULL,'2','2017-08-26 00:41:14','2017-08-26 00:41:14',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('34','0.01','1',NULL,'1','2017-08-26 11:57:26','2017-08-26 11:57:26',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('35','0.01','1',NULL,'1','2017-08-26 12:21:39','2017-08-26 12:21:39',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('36','0.01','1',NULL,'1','2017-08-26 12:34:46','2017-08-26 12:34:46',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('37','0.01','1',NULL,'2','2017-08-26 12:47:44','2017-08-26 12:47:44',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('38','0.02','1',NULL,'2','2017-08-26 12:47:44','2017-08-26 12:47:44',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'yijia',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('973575777381515265',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,NULL,NULL,NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('973575777381515266','6998.00','1',NULL,'1','2018-03-13 23:05:28','2018-03-13 23:05:28',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('985735071682002944','300.00','1','0','1','2018-04-16 12:22:10','2018-04-16 12:22:10',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,NULL,'qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('985897714950602752','0.01','1','0','1','2018-04-16 23:08:27','2018-04-16 23:08:27',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('986101214070439936','0.01','1','0','2','2018-04-17 12:37:05','2018-04-17 12:38:56','2018-04-17 12:38:56',NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('997428482541617152','995.00','1',NULL,'1','2018-05-18 18:47:36','2018-05-18 18:47:36',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('997787662276362240','0.01','1',NULL,'1','2018-05-19 18:34:51','2018-05-19 18:34:51',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('997790722834825216','0.01','1',NULL,'2','2018-05-19 18:47:01','2018-05-19 18:47:01','2018-05-19 18:47:18',NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('997791991808917504','0.01','1',NULL,'2','2018-05-19 18:52:04','2018-05-19 18:52:04','2018-05-19 18:52:12',NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('1016988259286384640','0.03',NULL,NULL,'1','2018-07-11 18:11:10','2018-07-11 18:11:10',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('1017351343561637888','0.01','1',NULL,'1','2018-07-12 18:13:56','2018-07-12 18:13:56',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('1017352971782062080','0.01','1',NULL,'2','2018-07-12 18:20:25','2018-07-12 18:21:35','2018-07-12 18:21:35',NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
insert into `tb_order` (`order_id`, `payment`, `payment_type`, `post_fee`, `status`, `create_time`, `update_time`, `payment_time`, `consign_time`, `end_time`, `close_time`, `shipping_name`, `shipping_code`, `user_id`, `buyer_message`, `buyer_nick`, `buyer_rate`, `receiver_area_name`, `receiver_mobile`, `receiver_zip_code`, `receiver`, `expire`, `invoice_type`, `source_type`, `seller_id`, `order_id_str`) values('1017354698660904960','0.01','1',NULL,'1','2018-07-12 18:27:16','2018-07-12 18:27:16',NULL,NULL,NULL,NULL,NULL,NULL,'zhangsanfeng',NULL,NULL,NULL,'你猜','13888888888',NULL,'尼采',NULL,NULL,'2','qiandu',NULL);
